### ISSUE TITLE
network_mode: "host" and 'internal0' device

### ISSUE THREAD

**Issue by robonuka** [cloudycube/docker-strongswan#4]
If I run it with network_mode: "host" it can create 'internal0' device only once. With the first start.
If I stop, remove and then start container again - I get this error:
---
```
2019-05-31 14:54:17.683557 [info] Configuring networking...
Traceback (most recent call last):
  File "/docker-startup/10-initial.startup/startup", line 14, in <module>
    exitcode = App.run()
  File "/docker-startup/10-initial.startup/gp_startup/gp_app.py", line 169, in run
    return App.instance.run()
  File "/docker-startup/10-initial.startup/gp_startup/gp_app.py", line 55, in run
    code = processor.process(tuple(argv[1:]))
  File "/docker-startup/10-initial.startup/gp_startup/gp_cmdproc.py", line 312, in process
    exitcode = handler(specified_positional_arguments, effective_named_arguments)
  File "/docker-startup/10-initial.startup/gp_startup/plugins/gp_cmdproc_vpn.py", line 679, in run
    self.__run_configure(pos_args, named_args)
  File "/docker-startup/10-initial.startup/gp_startup/plugins/gp_cmdproc_vpn.py", line 923, in __run_configure
    run(["ip", "link", "add", "internal0", "type", "dummy"], check=True, stdout=DEVNULL)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ip', 'link', 'add', 'internal0', 'type', 'dummy']' returned non-zero exit status 2.
```
---
You did the best Strongswan docker ever! Please fix that annoying bug :(
Now I must restart whole server if I need to restart Strongswan container :((

**Comment by ravenpride** [comment]
Thank you for your report and sorry for me replying that late. The notification that an issue has been filed seems to have been lost somewhere. I'll have a look at the issue.

**Comment by ravenpride** [comment]
Ok, I now see why this issue occurs. When starting with host networking, docker shares the network namespace of the host with the strongswan container, i.e. devices created within the container are actually created in the host's network namespace. That is why the first run succeeds and subsequent runs fail with the observed error message. The strongswan container was designed to work as described in the documentation.

Running with host networking enabled can cause a few side-effects you might not want. The strongswan container sets up a few firewall rules to handle isolation between clients and between the client and the internet. To realize these features dummy devices are used. These devices are created in the network namespace the container is associated with. If the container is running with host networking the configuration of firewall rules can screw up the firewall setup of your host.

Please keep that in mind.

**Comment by ravenpride** [comment]
I thought about the problem for some time and came to the conclusion that it makes no sense to support host networking. The strongswan container adds firewall rules that also apply to the default device and can have uncontrollable effects on the operation of other services on the host and last but not least the network function of Docker itself.

To get an idea, what the container actually does, have a look at this [method](https://github.com/GriffinPlus/docker-strongswan/blob/c17bd96ff670bf794c4eb49ffbd4c73b4a9134b4/target/docker-startup/10-initial.startup/gp_startup/plugins/gp_cmdproc_vpn.py#L831).

But I'm happy to try to help you with your deployment scenario. Can you please tell me more about it?

**Comment by ravenpride** [comment]
Due to one year of inactivity, I'll close the issue now. Please feel free to re-open it, if necessary.
