### ISSUE TITLE
linux client configugation

### ISSUE THREAD

**Issue by Perchework** [cloudycube/docker-strongswan#5]
Hi,

First, thank you for your work on this image!

I've deployed your Ipsec container in my swarm cluster, it's work well with an android client.
But, with my linux (ubuntu 18.04) laptop, it's more difficult to find the good configuration.
Did you have an ipsec.conf sample ?

For the moment, IKE is OK, but CHILD_SA is KO:
```
received FAILED_CP_REQUIRED notify, no CHILD_SA built
failed to establish CHILD_SA, keeping IKE_SA
```

I continue to search the good configuration and if I found, i send it.
But if you have some sample or advice, it's could be cool!

Thomas.

**Comment by Perchework** [comment]
More information from charon.log in your container:

```
Aug 27 07:29:41 12[IKE] <IKEv2-EAP-TLS|1> expected a virtual IP request, sending FAILED_CP_REQUIRED
Aug 27 07:29:41 02[JOB] next event in 19s 644ms, waiting
Aug 27 07:29:41 12[CFG] <IKEv2-EAP-TLS|1> looking for a child config for 0.0.0.0/0 === 10.29.255.201/32
Aug 27 07:29:41 12[CFG] <IKEv2-EAP-TLS|1> proposing traffic selectors for us:
Aug 27 07:29:41 12[CFG] <IKEv2-EAP-TLS|1>  0.0.0.0/0
Aug 27 07:29:41 12[CFG] <IKEv2-EAP-TLS|1>  ::/0
Aug 27 07:29:41 12[CFG] <IKEv2-EAP-TLS|1> proposing traffic selectors for other:
Aug 27 07:29:41 12[CFG] <IKEv2-EAP-TLS|1>  dynamic
Aug 27 07:29:41 12[IKE] <IKEv2-EAP-TLS|1> traffic selectors 0.0.0.0/0 === 10.29.255.201/32 unacceptable
Aug 27 07:29:41 12[IKE] <IKEv2-EAP-TLS|1> failed to establish CHILD_SA, keeping IKE_SA
```

I think my problem come from virtual IP.
Thanks!

**Comment by Perchework** [comment]
Found it, 

`leftsourceip=%config` is missing in my config.

Here is my working ipsec.conf:
```
conn %default
        ikelifetime=60m
        keylife=20m
        rekeymargin=3m
        keyingtries=1
        keyexchange=ikev2

conn ic1
        authby = pubkey
        eap_identity = %any
        left=%defaultroute
        leftauth=eap-tls
        leftsourceip=%config
        leftid="CN=XXX@XXX.XX, OU=XX, O=XXXXXXXX, C=FR"
        leftsendcert=always
        leftfirewall=yes
        right=xxx.xxx.xxx.xxx
        rightsubnet = 0.0.0.0/0
        rightid=%any
        ike = aes128gcm8-aes128gcm12-aes128gcm16-aes256gcm8-aes256gcm12-aes256gcm16-aes128ccm8-aes128ccm12-aes128ccm16-aes256ccm8-aes256ccm12-aes256ccm16-prfmd5-prfsha1-prfaesxcbc-prfaescmac-prfsha256-prfsha384$
        esp = aes128gcm8-aes128gcm12-aes128gcm16-aes256gcm8-aes256gcm12-aes256gcm16-aes128ccm8-aes128ccm12-aes128ccm16-aes256ccm8-aes256ccm12-aes256ccm16-modp2048-modp3072-modp4096-modp6144-modp8192-ecp192-ecp2$
        auto=add
```

Now the VPN work well in my laptop, I can ping all my container in the network.
My last problème (I think is not coming from the VPN) is DNS.
If I do `dig serviceName`, I get an IP (and I can ping this IP and access the service from this IP)
But if I do `ping serviceName`, I can't resolve the DNS name.

**Comment by Perchework** [comment]
All is good now!

The DNS problem on my ubuntu laptop come from the `libnss-mdns` package.
All works perfectly after removing it.

Thanks again for all your work !

**Comment by ravenpride** [comment]
I'm glad it's working. Thank you for the info.
