### ISSUE TITLE
use container with docker swarm (overlay network and swarm service) 

### ISSUE THREAD

**Issue by Perchework** [cloudycube/docker-strongswan#6]
Hi,

I use this container to access services in a docker swarm cluster.
With swarm, I need to use overlay network.

The container doesn't work with overlay network.
As a workaround, I create a bridge network to start the container (as say in the README) and after I connect the container to an overlay network and it's work well.

As a new feature, it's could be cool if we could start the container in a swarm service ?

**Comment by ravenpride** [comment]
Hi and thank you for the suggestion. I work with Docker and Kubernetes regularly, but Swarm is new territory for me. Can you tell me what is needed to start a container as a Swarm service?

**Comment by ravenpride** [comment]
Hmm, overlay networks seem to work just as user-defined networks in a single-node case. As long as port 500/UDP and 4500/UDP are reachable from the internet, you should be able to connect to strongswan.

Things to check that come to my mind:
- Do you connect to the IPv4 or IPv6 endpoint? - IPv4 is often a bit tricky due to NAT.
- Is the firewall configured to let port 500/UDP and 4500/UDP pass?
- Are the ports published on the container? - They should be, at least when connected to the bridge.

**Comment by Perchework** [comment]
I look a bit more.
For swarm service, I think is not possible for the moment as we can't set capabilities (--cap-add) or security-opt.

For overlay network, this driver permit to connect to multiple docker deamon. It's the default driver to use with swarm cluster.
This driver create multiple interface:
eth0 for the overlay network and eth1 for exposed ports.

If I use overlay network with your container, packets on port 500 and 4500 arrived on eth1, but strongswan listen on eth0.

It's not a real problem as I can start the container with a bridge network, and connect it after to an overlay.

Sorry for my bad english ;)

**Comment by ravenpride** [comment]
No problem - I'm not a native speaker either :-)

1) Can you run containers in privileged mode? That would solve the problem with capabilities and security options.

2) Yep you're right. Strongswan listens to packets coming from eth0 (see [here](https://github.com/GriffinPlus/docker-strongswan/blob/fd884e3f763ae4cfb5f5e240beea6844468ac562/target/etc/strongswan.conf.mako#L8)). You could try to set it to `eth1` or remove the line entirely. Strongswan listens to all interfaces and ignores packets that do not come in over the specified interface(s), so omitting `interfaces_use` could be an option, too. It should not cause any harm to listen to both eth0 and eth1.

**Comment by ravenpride** [comment]
Could you find out whether this works for you? - If it works, I will add an environment variable to configure the interface, so you get a clean solution for it.

**Comment by Perchework** [comment]
Hi,

It's working when I remove interfaces_use, and it's work too with interfaces_use = eth1.
Thanks for the help!

If you set it with an environment variable, an option to listen on all interface could be good as a container get one interface per overlay network: if you are connected to 4 overlay networks, you got 4 network interface.

**Comment by ravenpride** [comment]
Great, I'm glad it works for you!
I'll integrate the option as soon as I find the time - next weekend at the latest.

**Comment by ravenpride** [comment]
@Perchework I've finished the implementation, see [commit](https://github.com/GriffinPlus/docker-strongswan/commit/62e5f64fe69a31538818a0b454dbc96f1a87f5c9).

You can now set environment variable `USE_INTERFACES` to `eth0,eth1` to let strongswan listen to `eth0` and `eth1` only or specify `all` to listen to all interfaces available in the container.

Could you please check whether this works for you?

**Comment by Perchework** [comment]
I've juste test it, it's work with "all", and with "eth0,eth1"

Thank you!

**Comment by ravenpride** [comment]
You're welcome. And it is also a good addition to the project.

Have a nice week.

Closed.
