### ISSUE TITLE
Can the container run without IPv6?

### ISSUE THREAD

**Issue by per-bohlin** [cloudycube/docker-strongswan#9]
Hi,

Can the container be configured to run without IPv6?

**Comment by ravenpride** [comment]
Hi @per-bohlin,
the container is designed to work in a dual-stack environment with IPv4 and IPv6. The startup script configures the firewall für IPv4 and IPv6 appropriately. It would fail, if the system does not support both. But I think the script could be modified to support this. At the moment I have only little time for it, but would be happy to assist you, if you would like to adjust the scripts.

**Comment by per-bohlin** [comment]
Thank you for the quick reply and the offer to help but another complication is that the primary use case is site-to-site (see #8). So I will not be helped by disabling IPv6 - only.

I'm in a bit of a time crunch to get it up and running so I will probably go with another image that is built for IPv4 and site-to-site by design.

I started to look at your implementation because it looked very competent and had a lot of interesting features. When things has settled down I might return to it to use it for home in which I would have to disable IPv6. I will make a point to ask for hints if I do decide to take it.

Thanks again for taking an interest and for contributing to the opensource community.
